id = "Fiber-snippets"
name = "Fiber Snippets"
version = "0.1.0"
schema_version = 1
authors = ["Ayberk Gezer <ayberkgezer@outlook.com>"]
description = "Fiber v2 snippets for Zed IDE."
repository = "https://github.com/ayberkgezer/fiber-zed-snippets"
snippets = "./snippets/go.json"
